[package]
name = "tmux-helper"
version = "0.3.5"
description = "Utility for printing system info for tmux status line."
authors = ["Ultra Desu <ultradesu@hexor.ru>"]
edition = "2021"

[dependencies]
sys-info = "*"
dbus = "*"
chrono = "*"
mpd = "*"
clap = "*"
size_format = "1.0"
