[package]
name = "tmux-helper"
version = "0.4.0"
description = "Utility for printing system info for tmux status line."
authors = ["Ultra Desu <ultradesu@hexor.ru>"]
edition = "2021"

[dependencies]
sysinfo = "0.36.0"
dbus = "0.9"
chrono = "0.4"
mpd = "0.1"
clap = "4"
size_format = "1"
