name: Rust

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose --release
      env:
        RUST_BACKTRACE: 1
    - name: Strip
      run: strip target/release/tmux-helper

