name: Rust

on: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Pre-build
      run: sudo apt install -y libdbus-1-dev pkg-config libdbus-1-3
    - name: Build
      run: cargo build --verbose --release
      env:
        RUST_BACKTRACE: 1
    - name: Strip
      run: strip target/release/tmux-helper
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: target/release/tmux-helper application/x-pie-executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
